### ISSUE TITLE
problematic api: api/protected/jobs?order=asc

### ISSUE THREAD

**Issue by mStack5522** [eurekaclinical/eurekaclinical-protempa-service#15]
Query parameter **_order_**'s value equals to **_asc_**
Actually result is:
`Invalid value for the order parameter: asc`
Expecting result is:
A list of jobs, same as if there is no **_order_** query parameter

**Comment by arpost** [comment]
The default is unordered. Please implement support for ascending order when order=asc.

**Comment by mStack5522** [comment]
I already have the fix, but wait for you to merge the existing Pull Request and release a new version first before I push this fix onto GitHub

**Comment by mStack5522** [comment]
Pull request for this has been merged, hence closing this issue
