### ISSUE TITLE
problematic api: api/protected/jobs/status?jobId=jobId&userId=userId&state=foo&from=bar&to=baz

### ISSUE THREAD

**Issue by mStack5522** [eurekaclinical/eurekaclinical-protempa-service#16]
1. Query parameter **_&from=bar_** and **_to=baz_** do not have any effect on the result 
2. Query parameter _**jobId**_ only works if it equals to 1, if it equals 2 for example, the result is the same as if it equals to 1

**Comment by arpost** [comment]
Is this call used anywhere? If not, remove it. If it is, let me know where.

**Comment by mStack5522** [comment]
Pull request has been merged, hence close this issue
