### ISSUE TITLE
problematic api: api/protected/jobs/{jobId}/stats[/{key}]

### ISSUE THREAD

**Issue by mStack5522** [eurekaclinical/eurekaclinical-protempa-service#18]
This endpoint cannot be tested because no suitable value for {key} can be found.
Do we still need this endpoint? If not, we need to remove it from our document.

**Comment by arpost** [comment]
Please remove it from the documentation, and take out the /stats resource altogether. It is no longer used anywhere.

**Comment by mStack5522** [comment]
Done
